### ISSUE TITLE
Tried setting it up on AWS

### ISSUE THREAD

**Issue by TheKnarf** [barumel/docker-astroneer-server#12]
`compose.yml`:

```yaml
services:
  server:
    image: "barumel/docker-astroneer-server:latest"
    environment:
      - "ASTRO_SERVER_PUBLIC_IP=${ASTRO_SERVER_PUBLIC_IP}"
      - "ASTRO_SERVER_DOMAIN_NAME=${ASTRO_SERVER_DOMAIN_NAME}"
      - "ASTRO_SERVER_PORT=${ASTRO_SERVER_PORT:-8777}"
      - "ASTRO_SERVER_NAME=${ASTRO_SERVER_NAME}"
      - "ASTRO_SERVER_PASSWORD=${ASTRO_SERVER_PASSWORD}"
      - "ASTRO_SERVER_OWNER_NAME=${ASTRO_SERVER_OWNER_NAME}"
    ports:
      - ${ASTRO_SERVER_PORT:-8777}:${ASTRO_SERVER_PORT:-8777}/tcp
      - ${ASTRO_SERVER_PORT:-8777}:${ASTRO_SERVER_PORT:-8777}/udp
#    restart: unless-stopped
    volumes:
     - astroneer:/astroneer
     - steamcmd:/steamcmd
     - backup:/backup

volumes:
  astroneer:
  steamcmd:
  backup:
```

I've set  the following env variables `ASTRO_SERVER_NAME`, `ASTRO_SERVER_OWNER_NAME`, `ASTRO_SERVER_PASSWORD`.

`docker compose up -d`:
```
server-1  | REMOVE XVFB LOCK FILE IF IT EXISTS
server-1  | DONE...
server-1  | Found CPU with 2499.996 MHz
server-1  | UPDATE STEAM CMD
server-1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
server-1  | Logging directory: '/home/steam/Steam/logs'
server-1  | [  0%] Checking for available updates...
server-1  | [----] Verifying installation...
server-1  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1733269577
server-1  | -- type 'quit' to exit --
server-1  | Loading Steam API...IPC function call IClientUtils::GetConnectedUniverse took too long: 53 msec
server-1  | IPC function call IClientUtils::GetIPCountry took too long: 50 msec
server-1  | OK
server-1  | UPDATE ASTRO SERVER
server-1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
server-1  | Logging directory: '/home/steam/Steam/logs'
server-1  | [  0%] Checking for available updates...
server-1  | [----] Verifying installation...
server-1  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1733269577
server-1  | -- type 'quit' to exit --
server-1  | Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 43 msec
server-1  | OK
server-1  | @sSteamCmdForcePlatformType windows
server-1  | "@sSteamCmdForcePlatformType" = "windows"
server-1  | @sSteamCmdForcePlatformBitness 64
server-1  | "@sSteamCmdForcePlatformBitness" = "64"
server-1  | force_install_dir /astroneer
server-1  |
server-1  | Connecting anonymously to Steam Public...OK
server-1  | Waiting for client config...OK
server-1  | Waiting for user info...OK
server-1  | app_update 728470 validate
server-1  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
server-1  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
server-1  | Error! App '728470' state is 0x202 after update job.
server-1  | quit
server-1  | Server seems to run the first time!
server-1  | Start the server once to make sure all config files were created...
server-1  | esync: up and running.
server-1 exited with code 1
```

neofetch:

```
$ neofetch
            .-/+oossssoo+/-.               ubuntu@ip-10-10-1-162
        `:+ssssssssssssssssss+:`           ---------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.5 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: t3.medium
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.8.0-1019-aws
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 38 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 705 (dpkg), 6 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 800x600
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Platinum 8259CL (2) @ 2.499GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 00:03.0 Amazon.com, Inc. Device 1111
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 301MiB / 3836MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
